### ISSUE TITLE
Database Structure for Permission Tables

### ISSUE THREAD

**Issue by JamesItSolutionsLtd** [Arminkhodaei/Identity-Permission-Extension#1]
I already have my identity aspnet tables created as part of a existing project.

would be nice to have a db script to create the tables required for the new permission tables.

**Comment by Arminkhodaei** [comment]
Hello James,
You can update your existing database schema and tables using **EF Migration** commands, even if there are multiple Db Contexts in your application.
You can go through the link below, and see how you can update your existing database with only three commands:

**http://stackoverflow.com/a/21538091/1331197**

Also, you can create a PowerShell script to automatically run these three commands.
