### ISSUE TITLE
Example.mdf

### ISSUE THREAD

**Issue by luchendimple** [Arminkhodaei/Identity-Permission-Extension#2]
sorry,Can you provide this file?

**Comment by Arminkhodaei** [comment]
Hi @luchendimple, Is there any problem with creating the Db schema using the ef model first schema generator?
Here is the instruction just in case:

1) open the "Package Manager Console" window in visual studio.
2) choose "Example" project as the "Default Project".
3) run the following commands one by one:
. `Enable-Migrations`
. `Add-Migration Initial`
. `Update-Database`

PS: if you want to use the MSSQL LocalDB, make sure that have writing access to the current directory or modify the 'DefaultConnection' from `Web.config` file and point it to your DB instance.
